# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonPress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=30)),
                ('date_time', models.DateTimeField()),
                ('device_guid', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.CharField(max_length=30)),
                ('date_time', models.DateTimeField()),
                ('device_guid', models.CharField(max_length=100)),
            ],
        ),
    ]
