# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 12:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buttonpress',
            old_name='device_guid',
            new_name='guid',
        ),
        migrations.RenameField(
            model_name='buttonpress',
            old_name='date_time',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='temperature',
            old_name='device_guid',
            new_name='guid',
        ),
        migrations.RenameField(
            model_name='temperature',
            old_name='date_time',
            new_name='time',
        ),
    ]
